# Generated by Django 5.2.8 on 2026-06-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Order', max_length=255),
        ),
    ]
